// File generated by FlutterFire CLI — replace by running:
//   dart pub global activate flutterfire_cli
//   flutterfire configure --project=YOUR_PROJECT --platforms=android,ios
//
// Until then, Firebase.initializeApp runs without DefaultFirebaseOptions
// when [FirebaseOptions] are unavailable (see main.dart).

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Placeholder options. Replace via `flutterfire configure`.
class DefaultFirebaseOptions {
  static bool get isConfigured => false;

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web is out of MVP scope.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Dummy placeholders — flutterfire configure will overwrite these.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: '1:000000000000:android:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'bilbax-app',
    storageBucket: 'bilbax-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'bilbax-app',
    storageBucket: 'bilbax-app.appspot.com',
    iosBundleId: 'com.nextgenai.billbax',
  );
}
